version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./public:/var/www/public
      - ./src:/var/www/src
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      target: symfony_php
    depends_on:
      - db
    volumes:
      - ./public:/var/www/public
      - ./src:/var/www/src
      - ./tests:/var/www/tests
      - ./vendor:/var/www/vendor
      - ./migrations:/var/www/migrations
      - ./var:/var/www/var
      - ./templates:/var/www/templates
      - ./config:/var/www/config
      - ./bin:/var/www/bin
      - ./.env:/var/www/.env
      - ./.env.test:/var/www/.env.test
      - ./phpunit.xml.dist:/var/www/phpunit.xml.dist
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./phpstan.neon:/var/www/phpstan.neon

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: familymeet
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - '11080:8080'

volumes:
  db_data: {}
